version: '3.8'

services:
  processor:
    container_name: ${PROJECT_NAME}-processor
    build: .
    env_file:
        - .env
    ports:
      - "9010:9010"
    environment:
      - PYTHONPATH=/srv/app
    volumes:
      - ./api:/srv/app
    restart: unless-stopped
    networks:
      - api_network

networks:
  api_network:
    name: substream-network
    external: true